import type { Metadata } from "next";
import { Space_Grotesk } from '@next/font/google';
import "./globals.css";
import { space } from "postcss/lib/list";

const Space = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300','400', '700'],
  display: 'swap',
  variable: '--font-space-grotesk',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Space.className} antialiased bg-[#F0F0F0]`}
      >
        {children}
      </body>
    </html>
  );
}
